name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1
        with:
          always-auth: false
          # node-version: "16.x"  # Uncomment and set your version
          # registry-url: https://registry.npmjs.org/  # Optional
          # scope: '@your-scope'  # Optional
          # cache: npm  # Optional

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: my-artifact  # Set your artifact name
          path: path/to/artifact  # Set your path
          if-no-files-found: warn
          retention-days: 7
          compression-level: 6
          overwrite: false
          include-hidden-files: false

      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: '17'
          distribution: 'temurin'
          overwrite-settings: true

      - name: Setup Go environment
        uses: actions/setup-go@v5.5.0
        with:
          go-version: '1.20'  # Specify your Go version
          cache: true

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.4.2
        with:
          dotnet-version: '6.0.x'  # Specify your .NET SDK version
